### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by hokoo** [hokoo/safety-passwords#6]
Uncaught TypeError: count(): Argument 1 ($value) must be of type Countable|array, null given in /srv/web/safetypasswords/app/wp-content/plugins/safety-passwords/src/Controller.php:237

**Comment by hokoo** [comment]
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /srv/web/app/wp-content/mu-plugins/safety-passwords/src/Controller.php:264
Stack trace:
#0 /srv/web/app/wp-content/mu-plugins/safety-passwords/src/Controller.php(264): count()
#1 /srv/web/app/wordpress/wp-includes/class-wp-hook.php(324): iTRON\SafetyPasswords\Controller::findExpiringPasswords()
#2 /srv/web/app/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /srv/web/app/wordpress/wp-includes/plugin.php(565): WP_Hook->do_action()
#4 /srv/web/app/wordpress/wp-cron.php(191): do_action_ref_array()
#5 {main}
  thrown in /srv/web/app/wp-content/mu-plugins/safety-passwords/src/Controller.php on line 264
